version: "3.8"
services:
  app:
    build: .
    container_name: limeapi_app
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - API_PORT=${API_PORT:-3000}
      - ETH_NODE_URL=${ETH_NODE_URL}
      - DB_CONNECTION_URL=${DB_CONNECTION_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    networks:
      - limeapi_network
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:15-alpine
    container_name: limeapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - limeapi_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  limeapi_network:

volumes:
  postgres_data:
